// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qn7Ho0JKeaK-6KsXQZTJGGHZCQWEYZU',
    appId: '1:452007456438:web:33e4619baba0a1ddd9c017',
    messagingSenderId: '452007456438',
    projectId: 'flutterchat-da678',
    authDomain: 'flutterchat-da678.firebaseapp.com',
    storageBucket: 'flutterchat-da678.appspot.com',
    measurementId: 'G-ZLGJRLHKWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD7k9SEKVExJnWPp2IEQ1YfSs_WjW4yKg',
    appId: '1:452007456438:android:98cf6527dfcbb7bad9c017',
    messagingSenderId: '452007456438',
    projectId: 'flutterchat-da678',
    storageBucket: 'flutterchat-da678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1YgM6rE0CRsH6XSa8ifMMb7wYFCFLaw0',
    appId: '1:452007456438:ios:f91f1ccb3a4e8846d9c017',
    messagingSenderId: '452007456438',
    projectId: 'flutterchat-da678',
    storageBucket: 'flutterchat-da678.appspot.com',
    iosBundleId: 'com.example.fchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1YgM6rE0CRsH6XSa8ifMMb7wYFCFLaw0',
    appId: '1:452007456438:ios:59a85c6d8ed1227ed9c017',
    messagingSenderId: '452007456438',
    projectId: 'flutterchat-da678',
    storageBucket: 'flutterchat-da678.appspot.com',
    iosBundleId: 'com.example.fchat.RunnerTests',
  );
}
